# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: patient_service.proto

require 'google/protobuf'

#Define o descriptor para o GRPC
descriptor_data = "\n\x15patient_service.proto\x12\x0cgrpc_patient\"2\n\x0ePatientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nbirth_date\x18\x02 \x01(\t\"\"\n\x0fPatientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\x0ePatientService\x12I\n\nAddPatient\x12\x1c.grpc_patient.PatientRequest\x1a\x1d.grpc_patient.PatientResponseb\x06proto3"

#Define o pool para o GRPC
pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)
    
#Define o módulo para o GRPC
module GrpcPatient
  #Define o request para o GRPC
  PatientRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_patient.PatientRequest").msgclass
  #Define o response para o GRPC
  PatientResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_patient.PatientResponse").msgclass
end
