# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: patient_service.proto for package 'grpc_patient'

require 'grpc'
require_relative 'patient_service_pb'

#Modulo para o GRPC
module GrpcPatient
  module PatientService
    class Service

      #Inclui o GenericService do GRPC
      include ::GRPC::GenericService

      #Define o método marshal e unmarshal para o GRPC  
      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode

      #Define o nome do serviço para o GRPC
      self.service_name = 'grpc_patient.PatientService'

      #Define o método AddPatient para o GRPC
      rpc :AddPatient, ::GrpcPatient::PatientRequest, ::GrpcPatient::PatientResponse
    end

    #Define o stub para o GRPC
    Stub = Service.rpc_stub_class
  end
end
